/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuppliersIdRouteImport } from './routes/suppliers.$id'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AuthenticatedWishlistRouteImport } from './routes/_authenticated/wishlist'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedAddressesRouteImport } from './routes/_authenticated/addresses'
import { Route as AuthenticatedSupplierIndexRouteImport } from './routes/_authenticated/supplier.index'
import { Route as AuthenticatedSupplierWarehouseRouteImport } from './routes/_authenticated/supplier.warehouse'
import { Route as AuthenticatedSupplierSupportRouteImport } from './routes/_authenticated/supplier.support'
import { Route as AuthenticatedSupplierSettingsRouteImport } from './routes/_authenticated/supplier.settings'
import { Route as AuthenticatedSupplierReviewsRouteImport } from './routes/_authenticated/supplier.reviews'
import { Route as AuthenticatedSupplierPromotionsRouteImport } from './routes/_authenticated/supplier.promotions'
import { Route as AuthenticatedSupplierProfileRouteImport } from './routes/_authenticated/supplier.profile'
import { Route as AuthenticatedSupplierPricingRouteImport } from './routes/_authenticated/supplier.pricing'
import { Route as AuthenticatedSupplierOrdersRouteImport } from './routes/_authenticated/supplier.orders'
import { Route as AuthenticatedSupplierNotificationsRouteImport } from './routes/_authenticated/supplier.notifications'
import { Route as AuthenticatedSupplierInventoryRouteImport } from './routes/_authenticated/supplier.inventory'
import { Route as AuthenticatedSupplierDocumentsRouteImport } from './routes/_authenticated/supplier.documents'
import { Route as AuthenticatedSupplierCustomersRouteImport } from './routes/_authenticated/supplier.customers'
import { Route as AuthenticatedSupplierAnalyticsRouteImport } from './routes/_authenticated/supplier.analytics'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders.$id'
import { Route as AuthenticatedSupplierProductsIndexRouteImport } from './routes/_authenticated/supplier.products.index'
import { Route as AuthenticatedSupplierProductsNewRouteImport } from './routes/_authenticated/supplier.products.new'
import { Route as AuthenticatedSupplierProductsIdRouteImport } from './routes/_authenticated/supplier.products.$id'

const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIdRoute = SuppliersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SuppliersRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWishlistRoute = AuthenticatedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAddressesRoute = AuthenticatedAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupplierIndexRoute =
  AuthenticatedSupplierIndexRouteImport.update({
    id: '/supplier/',
    path: '/supplier/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierWarehouseRoute =
  AuthenticatedSupplierWarehouseRouteImport.update({
    id: '/supplier/warehouse',
    path: '/supplier/warehouse',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierSupportRoute =
  AuthenticatedSupplierSupportRouteImport.update({
    id: '/supplier/support',
    path: '/supplier/support',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierSettingsRoute =
  AuthenticatedSupplierSettingsRouteImport.update({
    id: '/supplier/settings',
    path: '/supplier/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierReviewsRoute =
  AuthenticatedSupplierReviewsRouteImport.update({
    id: '/supplier/reviews',
    path: '/supplier/reviews',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierPromotionsRoute =
  AuthenticatedSupplierPromotionsRouteImport.update({
    id: '/supplier/promotions',
    path: '/supplier/promotions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierProfileRoute =
  AuthenticatedSupplierProfileRouteImport.update({
    id: '/supplier/profile',
    path: '/supplier/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierPricingRoute =
  AuthenticatedSupplierPricingRouteImport.update({
    id: '/supplier/pricing',
    path: '/supplier/pricing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierOrdersRoute =
  AuthenticatedSupplierOrdersRouteImport.update({
    id: '/supplier/orders',
    path: '/supplier/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierNotificationsRoute =
  AuthenticatedSupplierNotificationsRouteImport.update({
    id: '/supplier/notifications',
    path: '/supplier/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierInventoryRoute =
  AuthenticatedSupplierInventoryRouteImport.update({
    id: '/supplier/inventory',
    path: '/supplier/inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierDocumentsRoute =
  AuthenticatedSupplierDocumentsRouteImport.update({
    id: '/supplier/documents',
    path: '/supplier/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierCustomersRoute =
  AuthenticatedSupplierCustomersRouteImport.update({
    id: '/supplier/customers',
    path: '/supplier/customers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierAnalyticsRoute =
  AuthenticatedSupplierAnalyticsRouteImport.update({
    id: '/supplier/analytics',
    path: '/supplier/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedOrdersRoute,
} as any)
const AuthenticatedSupplierProductsIndexRoute =
  AuthenticatedSupplierProductsIndexRouteImport.update({
    id: '/supplier/products/',
    path: '/supplier/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierProductsNewRoute =
  AuthenticatedSupplierProductsNewRouteImport.update({
    id: '/supplier/products/new',
    path: '/supplier/products/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierProductsIdRoute =
  AuthenticatedSupplierProductsIdRouteImport.update({
    id: '/supplier/products/$id',
    path: '/supplier/products/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/marketplace': typeof MarketplaceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suppliers': typeof SuppliersRouteWithChildren
  '/addresses': typeof AuthenticatedAddressesRoute
  '/cart': typeof AuthenticatedCartRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/supplier/analytics': typeof AuthenticatedSupplierAnalyticsRoute
  '/supplier/customers': typeof AuthenticatedSupplierCustomersRoute
  '/supplier/documents': typeof AuthenticatedSupplierDocumentsRoute
  '/supplier/inventory': typeof AuthenticatedSupplierInventoryRoute
  '/supplier/notifications': typeof AuthenticatedSupplierNotificationsRoute
  '/supplier/orders': typeof AuthenticatedSupplierOrdersRoute
  '/supplier/pricing': typeof AuthenticatedSupplierPricingRoute
  '/supplier/profile': typeof AuthenticatedSupplierProfileRoute
  '/supplier/promotions': typeof AuthenticatedSupplierPromotionsRoute
  '/supplier/reviews': typeof AuthenticatedSupplierReviewsRoute
  '/supplier/settings': typeof AuthenticatedSupplierSettingsRoute
  '/supplier/support': typeof AuthenticatedSupplierSupportRoute
  '/supplier/warehouse': typeof AuthenticatedSupplierWarehouseRoute
  '/supplier/': typeof AuthenticatedSupplierIndexRoute
  '/supplier/products/$id': typeof AuthenticatedSupplierProductsIdRoute
  '/supplier/products/new': typeof AuthenticatedSupplierProductsNewRoute
  '/supplier/products/': typeof AuthenticatedSupplierProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/marketplace': typeof MarketplaceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suppliers': typeof SuppliersRouteWithChildren
  '/addresses': typeof AuthenticatedAddressesRoute
  '/cart': typeof AuthenticatedCartRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/supplier/analytics': typeof AuthenticatedSupplierAnalyticsRoute
  '/supplier/customers': typeof AuthenticatedSupplierCustomersRoute
  '/supplier/documents': typeof AuthenticatedSupplierDocumentsRoute
  '/supplier/inventory': typeof AuthenticatedSupplierInventoryRoute
  '/supplier/notifications': typeof AuthenticatedSupplierNotificationsRoute
  '/supplier/orders': typeof AuthenticatedSupplierOrdersRoute
  '/supplier/pricing': typeof AuthenticatedSupplierPricingRoute
  '/supplier/profile': typeof AuthenticatedSupplierProfileRoute
  '/supplier/promotions': typeof AuthenticatedSupplierPromotionsRoute
  '/supplier/reviews': typeof AuthenticatedSupplierReviewsRoute
  '/supplier/settings': typeof AuthenticatedSupplierSettingsRoute
  '/supplier/support': typeof AuthenticatedSupplierSupportRoute
  '/supplier/warehouse': typeof AuthenticatedSupplierWarehouseRoute
  '/supplier': typeof AuthenticatedSupplierIndexRoute
  '/supplier/products/$id': typeof AuthenticatedSupplierProductsIdRoute
  '/supplier/products/new': typeof AuthenticatedSupplierProductsNewRoute
  '/supplier/products': typeof AuthenticatedSupplierProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/marketplace': typeof MarketplaceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suppliers': typeof SuppliersRouteWithChildren
  '/_authenticated/addresses': typeof AuthenticatedAddressesRoute
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/wishlist': typeof AuthenticatedWishlistRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/_authenticated/supplier/analytics': typeof AuthenticatedSupplierAnalyticsRoute
  '/_authenticated/supplier/customers': typeof AuthenticatedSupplierCustomersRoute
  '/_authenticated/supplier/documents': typeof AuthenticatedSupplierDocumentsRoute
  '/_authenticated/supplier/inventory': typeof AuthenticatedSupplierInventoryRoute
  '/_authenticated/supplier/notifications': typeof AuthenticatedSupplierNotificationsRoute
  '/_authenticated/supplier/orders': typeof AuthenticatedSupplierOrdersRoute
  '/_authenticated/supplier/pricing': typeof AuthenticatedSupplierPricingRoute
  '/_authenticated/supplier/profile': typeof AuthenticatedSupplierProfileRoute
  '/_authenticated/supplier/promotions': typeof AuthenticatedSupplierPromotionsRoute
  '/_authenticated/supplier/reviews': typeof AuthenticatedSupplierReviewsRoute
  '/_authenticated/supplier/settings': typeof AuthenticatedSupplierSettingsRoute
  '/_authenticated/supplier/support': typeof AuthenticatedSupplierSupportRoute
  '/_authenticated/supplier/warehouse': typeof AuthenticatedSupplierWarehouseRoute
  '/_authenticated/supplier/': typeof AuthenticatedSupplierIndexRoute
  '/_authenticated/supplier/products/$id': typeof AuthenticatedSupplierProductsIdRoute
  '/_authenticated/supplier/products/new': typeof AuthenticatedSupplierProductsNewRoute
  '/_authenticated/supplier/products/': typeof AuthenticatedSupplierProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/categories'
    | '/contact'
    | '/forgot-password'
    | '/marketplace'
    | '/reset-password'
    | '/suppliers'
    | '/addresses'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/help'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/profile'
    | '/settings'
    | '/wishlist'
    | '/products/$slug'
    | '/suppliers/$id'
    | '/orders/$id'
    | '/supplier/analytics'
    | '/supplier/customers'
    | '/supplier/documents'
    | '/supplier/inventory'
    | '/supplier/notifications'
    | '/supplier/orders'
    | '/supplier/pricing'
    | '/supplier/profile'
    | '/supplier/promotions'
    | '/supplier/reviews'
    | '/supplier/settings'
    | '/supplier/support'
    | '/supplier/warehouse'
    | '/supplier/'
    | '/supplier/products/$id'
    | '/supplier/products/new'
    | '/supplier/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/categories'
    | '/contact'
    | '/forgot-password'
    | '/marketplace'
    | '/reset-password'
    | '/suppliers'
    | '/addresses'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/help'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/profile'
    | '/settings'
    | '/wishlist'
    | '/products/$slug'
    | '/suppliers/$id'
    | '/orders/$id'
    | '/supplier/analytics'
    | '/supplier/customers'
    | '/supplier/documents'
    | '/supplier/inventory'
    | '/supplier/notifications'
    | '/supplier/orders'
    | '/supplier/pricing'
    | '/supplier/profile'
    | '/supplier/promotions'
    | '/supplier/reviews'
    | '/supplier/settings'
    | '/supplier/support'
    | '/supplier/warehouse'
    | '/supplier'
    | '/supplier/products/$id'
    | '/supplier/products/new'
    | '/supplier/products'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/categories'
    | '/contact'
    | '/forgot-password'
    | '/marketplace'
    | '/reset-password'
    | '/suppliers'
    | '/_authenticated/addresses'
    | '/_authenticated/cart'
    | '/_authenticated/checkout'
    | '/_authenticated/dashboard'
    | '/_authenticated/help'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/orders'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/wishlist'
    | '/products/$slug'
    | '/suppliers/$id'
    | '/_authenticated/orders/$id'
    | '/_authenticated/supplier/analytics'
    | '/_authenticated/supplier/customers'
    | '/_authenticated/supplier/documents'
    | '/_authenticated/supplier/inventory'
    | '/_authenticated/supplier/notifications'
    | '/_authenticated/supplier/orders'
    | '/_authenticated/supplier/pricing'
    | '/_authenticated/supplier/profile'
    | '/_authenticated/supplier/promotions'
    | '/_authenticated/supplier/reviews'
    | '/_authenticated/supplier/settings'
    | '/_authenticated/supplier/support'
    | '/_authenticated/supplier/warehouse'
    | '/_authenticated/supplier/'
    | '/_authenticated/supplier/products/$id'
    | '/_authenticated/supplier/products/new'
    | '/_authenticated/supplier/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  MarketplaceRoute: typeof MarketplaceRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuppliersRoute: typeof SuppliersRouteWithChildren
  ProductsSlugRoute: typeof ProductsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$id': {
      id: '/suppliers/$id'
      path: '/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof SuppliersIdRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wishlist': {
      id: '/_authenticated/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AuthenticatedWishlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/addresses': {
      id: '/_authenticated/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AuthenticatedAddressesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/': {
      id: '/_authenticated/supplier/'
      path: '/supplier'
      fullPath: '/supplier/'
      preLoaderRoute: typeof AuthenticatedSupplierIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/warehouse': {
      id: '/_authenticated/supplier/warehouse'
      path: '/supplier/warehouse'
      fullPath: '/supplier/warehouse'
      preLoaderRoute: typeof AuthenticatedSupplierWarehouseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/support': {
      id: '/_authenticated/supplier/support'
      path: '/supplier/support'
      fullPath: '/supplier/support'
      preLoaderRoute: typeof AuthenticatedSupplierSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/settings': {
      id: '/_authenticated/supplier/settings'
      path: '/supplier/settings'
      fullPath: '/supplier/settings'
      preLoaderRoute: typeof AuthenticatedSupplierSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/reviews': {
      id: '/_authenticated/supplier/reviews'
      path: '/supplier/reviews'
      fullPath: '/supplier/reviews'
      preLoaderRoute: typeof AuthenticatedSupplierReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/promotions': {
      id: '/_authenticated/supplier/promotions'
      path: '/supplier/promotions'
      fullPath: '/supplier/promotions'
      preLoaderRoute: typeof AuthenticatedSupplierPromotionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/profile': {
      id: '/_authenticated/supplier/profile'
      path: '/supplier/profile'
      fullPath: '/supplier/profile'
      preLoaderRoute: typeof AuthenticatedSupplierProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/pricing': {
      id: '/_authenticated/supplier/pricing'
      path: '/supplier/pricing'
      fullPath: '/supplier/pricing'
      preLoaderRoute: typeof AuthenticatedSupplierPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/orders': {
      id: '/_authenticated/supplier/orders'
      path: '/supplier/orders'
      fullPath: '/supplier/orders'
      preLoaderRoute: typeof AuthenticatedSupplierOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/notifications': {
      id: '/_authenticated/supplier/notifications'
      path: '/supplier/notifications'
      fullPath: '/supplier/notifications'
      preLoaderRoute: typeof AuthenticatedSupplierNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/inventory': {
      id: '/_authenticated/supplier/inventory'
      path: '/supplier/inventory'
      fullPath: '/supplier/inventory'
      preLoaderRoute: typeof AuthenticatedSupplierInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/documents': {
      id: '/_authenticated/supplier/documents'
      path: '/supplier/documents'
      fullPath: '/supplier/documents'
      preLoaderRoute: typeof AuthenticatedSupplierDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/customers': {
      id: '/_authenticated/supplier/customers'
      path: '/supplier/customers'
      fullPath: '/supplier/customers'
      preLoaderRoute: typeof AuthenticatedSupplierCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/analytics': {
      id: '/_authenticated/supplier/analytics'
      path: '/supplier/analytics'
      fullPath: '/supplier/analytics'
      preLoaderRoute: typeof AuthenticatedSupplierAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
    '/_authenticated/supplier/products/': {
      id: '/_authenticated/supplier/products/'
      path: '/supplier/products'
      fullPath: '/supplier/products/'
      preLoaderRoute: typeof AuthenticatedSupplierProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/products/new': {
      id: '/_authenticated/supplier/products/new'
      path: '/supplier/products/new'
      fullPath: '/supplier/products/new'
      preLoaderRoute: typeof AuthenticatedSupplierProductsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/products/$id': {
      id: '/_authenticated/supplier/products/$id'
      path: '/supplier/products/$id'
      fullPath: '/supplier/products/$id'
      preLoaderRoute: typeof AuthenticatedSupplierProductsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedOrdersRouteChildren {
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRoute
}

const AuthenticatedOrdersRouteChildren: AuthenticatedOrdersRouteChildren = {
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRoute,
}

const AuthenticatedOrdersRouteWithChildren =
  AuthenticatedOrdersRoute._addFileChildren(AuthenticatedOrdersRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAddressesRoute: typeof AuthenticatedAddressesRoute
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWishlistRoute: typeof AuthenticatedWishlistRoute
  AuthenticatedSupplierAnalyticsRoute: typeof AuthenticatedSupplierAnalyticsRoute
  AuthenticatedSupplierCustomersRoute: typeof AuthenticatedSupplierCustomersRoute
  AuthenticatedSupplierDocumentsRoute: typeof AuthenticatedSupplierDocumentsRoute
  AuthenticatedSupplierInventoryRoute: typeof AuthenticatedSupplierInventoryRoute
  AuthenticatedSupplierNotificationsRoute: typeof AuthenticatedSupplierNotificationsRoute
  AuthenticatedSupplierOrdersRoute: typeof AuthenticatedSupplierOrdersRoute
  AuthenticatedSupplierPricingRoute: typeof AuthenticatedSupplierPricingRoute
  AuthenticatedSupplierProfileRoute: typeof AuthenticatedSupplierProfileRoute
  AuthenticatedSupplierPromotionsRoute: typeof AuthenticatedSupplierPromotionsRoute
  AuthenticatedSupplierReviewsRoute: typeof AuthenticatedSupplierReviewsRoute
  AuthenticatedSupplierSettingsRoute: typeof AuthenticatedSupplierSettingsRoute
  AuthenticatedSupplierSupportRoute: typeof AuthenticatedSupplierSupportRoute
  AuthenticatedSupplierWarehouseRoute: typeof AuthenticatedSupplierWarehouseRoute
  AuthenticatedSupplierIndexRoute: typeof AuthenticatedSupplierIndexRoute
  AuthenticatedSupplierProductsIdRoute: typeof AuthenticatedSupplierProductsIdRoute
  AuthenticatedSupplierProductsNewRoute: typeof AuthenticatedSupplierProductsNewRoute
  AuthenticatedSupplierProductsIndexRoute: typeof AuthenticatedSupplierProductsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAddressesRoute: AuthenticatedAddressesRoute,
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWishlistRoute: AuthenticatedWishlistRoute,
  AuthenticatedSupplierAnalyticsRoute: AuthenticatedSupplierAnalyticsRoute,
  AuthenticatedSupplierCustomersRoute: AuthenticatedSupplierCustomersRoute,
  AuthenticatedSupplierDocumentsRoute: AuthenticatedSupplierDocumentsRoute,
  AuthenticatedSupplierInventoryRoute: AuthenticatedSupplierInventoryRoute,
  AuthenticatedSupplierNotificationsRoute:
    AuthenticatedSupplierNotificationsRoute,
  AuthenticatedSupplierOrdersRoute: AuthenticatedSupplierOrdersRoute,
  AuthenticatedSupplierPricingRoute: AuthenticatedSupplierPricingRoute,
  AuthenticatedSupplierProfileRoute: AuthenticatedSupplierProfileRoute,
  AuthenticatedSupplierPromotionsRoute: AuthenticatedSupplierPromotionsRoute,
  AuthenticatedSupplierReviewsRoute: AuthenticatedSupplierReviewsRoute,
  AuthenticatedSupplierSettingsRoute: AuthenticatedSupplierSettingsRoute,
  AuthenticatedSupplierSupportRoute: AuthenticatedSupplierSupportRoute,
  AuthenticatedSupplierWarehouseRoute: AuthenticatedSupplierWarehouseRoute,
  AuthenticatedSupplierIndexRoute: AuthenticatedSupplierIndexRoute,
  AuthenticatedSupplierProductsIdRoute: AuthenticatedSupplierProductsIdRoute,
  AuthenticatedSupplierProductsNewRoute: AuthenticatedSupplierProductsNewRoute,
  AuthenticatedSupplierProductsIndexRoute:
    AuthenticatedSupplierProductsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SuppliersRouteChildren {
  SuppliersIdRoute: typeof SuppliersIdRoute
}

const SuppliersRouteChildren: SuppliersRouteChildren = {
  SuppliersIdRoute: SuppliersIdRoute,
}

const SuppliersRouteWithChildren = SuppliersRoute._addFileChildren(
  SuppliersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  MarketplaceRoute: MarketplaceRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuppliersRoute: SuppliersRouteWithChildren,
  ProductsSlugRoute: ProductsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
