/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as SuppliersIdRouteImport } from './routes/suppliers.$id'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as AuthenticatedWishlistRouteImport } from './routes/_authenticated/wishlist'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSellerRouteImport } from './routes/_authenticated/seller'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedBuyerRouteImport } from './routes/_authenticated/buyer'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAddressesRouteImport } from './routes/_authenticated/addresses'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedSupplierWarehouseRouteImport } from './routes/_authenticated/supplier.warehouse'
import { Route as AuthenticatedSupplierSupportRouteImport } from './routes/_authenticated/supplier.support'
import { Route as AuthenticatedSupplierSettingsRouteImport } from './routes/_authenticated/supplier.settings'
import { Route as AuthenticatedSupplierReviewsRouteImport } from './routes/_authenticated/supplier.reviews'
import { Route as AuthenticatedSupplierReportsRouteImport } from './routes/_authenticated/supplier.reports'
import { Route as AuthenticatedSupplierPromotionsRouteImport } from './routes/_authenticated/supplier.promotions'
import { Route as AuthenticatedSupplierProfileRouteImport } from './routes/_authenticated/supplier.profile'
import { Route as AuthenticatedSupplierPricingRouteImport } from './routes/_authenticated/supplier.pricing'
import { Route as AuthenticatedSupplierPaymentsRouteImport } from './routes/_authenticated/supplier.payments'
import { Route as AuthenticatedSupplierOrdersRouteImport } from './routes/_authenticated/supplier.orders'
import { Route as AuthenticatedSupplierNotificationsRouteImport } from './routes/_authenticated/supplier.notifications'
import { Route as AuthenticatedSupplierInventoryRouteImport } from './routes/_authenticated/supplier.inventory'
import { Route as AuthenticatedSupplierDocumentsRouteImport } from './routes/_authenticated/supplier.documents'
import { Route as AuthenticatedSupplierCustomersRouteImport } from './routes/_authenticated/supplier.customers'
import { Route as AuthenticatedSupplierAnalyticsRouteImport } from './routes/_authenticated/supplier.analytics'
import { Route as AuthenticatedSellerDashboardRouteImport } from './routes/_authenticated/seller.dashboard'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders.$id'
import { Route as AuthenticatedBuyerDashboardRouteImport } from './routes/_authenticated/buyer.dashboard'
import { Route as AuthenticatedAdminVerificationsRouteImport } from './routes/_authenticated/admin.verifications'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSecurityRouteImport } from './routes/_authenticated/admin.security'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/admin.finance'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin.coupons'
import { Route as AuthenticatedAdminCmsRouteImport } from './routes/_authenticated/admin.cms'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin.banners'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedSupplierProductsIndexRouteImport } from './routes/_authenticated/supplier.products.index'
import { Route as AuthenticatedSupplierProductsNewRouteImport } from './routes/_authenticated/supplier.products.new'
import { Route as AuthenticatedSupplierProductsIdRouteImport } from './routes/_authenticated/supplier.products.$id'
import { Route as AuthenticatedSupplierOrdersIdRouteImport } from './routes/_authenticated/supplier.orders.$id'
import { Route as AuthenticatedSupplierCustomersIdRouteImport } from './routes/_authenticated/supplier.customers.$id'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoriesRoute,
} as any)
const SuppliersIdRoute = SuppliersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SuppliersRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoriesRoute,
} as any)
const AuthenticatedWishlistRoute = AuthenticatedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellerRoute = AuthenticatedSellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuyerRoute = AuthenticatedBuyerRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAddressesRoute = AuthenticatedAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSupplierWarehouseRoute =
  AuthenticatedSupplierWarehouseRouteImport.update({
    id: '/supplier/warehouse',
    path: '/supplier/warehouse',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierSupportRoute =
  AuthenticatedSupplierSupportRouteImport.update({
    id: '/supplier/support',
    path: '/supplier/support',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierSettingsRoute =
  AuthenticatedSupplierSettingsRouteImport.update({
    id: '/supplier/settings',
    path: '/supplier/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierReviewsRoute =
  AuthenticatedSupplierReviewsRouteImport.update({
    id: '/supplier/reviews',
    path: '/supplier/reviews',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierReportsRoute =
  AuthenticatedSupplierReportsRouteImport.update({
    id: '/supplier/reports',
    path: '/supplier/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierPromotionsRoute =
  AuthenticatedSupplierPromotionsRouteImport.update({
    id: '/supplier/promotions',
    path: '/supplier/promotions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierProfileRoute =
  AuthenticatedSupplierProfileRouteImport.update({
    id: '/supplier/profile',
    path: '/supplier/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierPricingRoute =
  AuthenticatedSupplierPricingRouteImport.update({
    id: '/supplier/pricing',
    path: '/supplier/pricing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierPaymentsRoute =
  AuthenticatedSupplierPaymentsRouteImport.update({
    id: '/supplier/payments',
    path: '/supplier/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierOrdersRoute =
  AuthenticatedSupplierOrdersRouteImport.update({
    id: '/supplier/orders',
    path: '/supplier/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierNotificationsRoute =
  AuthenticatedSupplierNotificationsRouteImport.update({
    id: '/supplier/notifications',
    path: '/supplier/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierInventoryRoute =
  AuthenticatedSupplierInventoryRouteImport.update({
    id: '/supplier/inventory',
    path: '/supplier/inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierDocumentsRoute =
  AuthenticatedSupplierDocumentsRouteImport.update({
    id: '/supplier/documents',
    path: '/supplier/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierCustomersRoute =
  AuthenticatedSupplierCustomersRouteImport.update({
    id: '/supplier/customers',
    path: '/supplier/customers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierAnalyticsRoute =
  AuthenticatedSupplierAnalyticsRouteImport.update({
    id: '/supplier/analytics',
    path: '/supplier/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSellerDashboardRoute =
  AuthenticatedSellerDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedOrdersRoute,
} as any)
const AuthenticatedBuyerDashboardRoute =
  AuthenticatedBuyerDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedBuyerRoute,
  } as any)
const AuthenticatedAdminVerificationsRoute =
  AuthenticatedAdminVerificationsRouteImport.update({
    id: '/verifications',
    path: '/verifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSecurityRoute =
  AuthenticatedAdminSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCmsRoute = AuthenticatedAdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedSupplierProductsIndexRoute =
  AuthenticatedSupplierProductsIndexRouteImport.update({
    id: '/supplier/products/',
    path: '/supplier/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierProductsNewRoute =
  AuthenticatedSupplierProductsNewRouteImport.update({
    id: '/supplier/products/new',
    path: '/supplier/products/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierProductsIdRoute =
  AuthenticatedSupplierProductsIdRouteImport.update({
    id: '/supplier/products/$id',
    path: '/supplier/products/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierOrdersIdRoute =
  AuthenticatedSupplierOrdersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedSupplierOrdersRoute,
  } as any)
const AuthenticatedSupplierCustomersIdRoute =
  AuthenticatedSupplierCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedSupplierCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/marketplace': typeof MarketplaceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suppliers': typeof SuppliersRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/addresses': typeof AuthenticatedAddressesRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/buyer': typeof AuthenticatedBuyerRouteWithChildren
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/help': typeof AuthenticatedHelpRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/seller': typeof AuthenticatedSellerRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/cms': typeof AuthenticatedAdminCmsRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/buyer/dashboard': typeof AuthenticatedBuyerDashboardRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/seller/dashboard': typeof AuthenticatedSellerDashboardRoute
  '/supplier/analytics': typeof AuthenticatedSupplierAnalyticsRoute
  '/supplier/customers': typeof AuthenticatedSupplierCustomersRouteWithChildren
  '/supplier/documents': typeof AuthenticatedSupplierDocumentsRoute
  '/supplier/inventory': typeof AuthenticatedSupplierInventoryRoute
  '/supplier/notifications': typeof AuthenticatedSupplierNotificationsRoute
  '/supplier/orders': typeof AuthenticatedSupplierOrdersRouteWithChildren
  '/supplier/payments': typeof AuthenticatedSupplierPaymentsRoute
  '/supplier/pricing': typeof AuthenticatedSupplierPricingRoute
  '/supplier/profile': typeof AuthenticatedSupplierProfileRoute
  '/supplier/promotions': typeof AuthenticatedSupplierPromotionsRoute
  '/supplier/reports': typeof AuthenticatedSupplierReportsRoute
  '/supplier/reviews': typeof AuthenticatedSupplierReviewsRoute
  '/supplier/settings': typeof AuthenticatedSupplierSettingsRoute
  '/supplier/support': typeof AuthenticatedSupplierSupportRoute
  '/supplier/warehouse': typeof AuthenticatedSupplierWarehouseRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/supplier/customers/$id': typeof AuthenticatedSupplierCustomersIdRoute
  '/supplier/orders/$id': typeof AuthenticatedSupplierOrdersIdRoute
  '/supplier/products/$id': typeof AuthenticatedSupplierProductsIdRoute
  '/supplier/products/new': typeof AuthenticatedSupplierProductsNewRoute
  '/supplier/products/': typeof AuthenticatedSupplierProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/marketplace': typeof MarketplaceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suppliers': typeof SuppliersRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/addresses': typeof AuthenticatedAddressesRoute
  '/buyer': typeof AuthenticatedBuyerRouteWithChildren
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/help': typeof AuthenticatedHelpRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/seller': typeof AuthenticatedSellerRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/categories': typeof CategoriesIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/cms': typeof AuthenticatedAdminCmsRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/buyer/dashboard': typeof AuthenticatedBuyerDashboardRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/seller/dashboard': typeof AuthenticatedSellerDashboardRoute
  '/supplier/analytics': typeof AuthenticatedSupplierAnalyticsRoute
  '/supplier/customers': typeof AuthenticatedSupplierCustomersRouteWithChildren
  '/supplier/documents': typeof AuthenticatedSupplierDocumentsRoute
  '/supplier/inventory': typeof AuthenticatedSupplierInventoryRoute
  '/supplier/notifications': typeof AuthenticatedSupplierNotificationsRoute
  '/supplier/orders': typeof AuthenticatedSupplierOrdersRouteWithChildren
  '/supplier/payments': typeof AuthenticatedSupplierPaymentsRoute
  '/supplier/pricing': typeof AuthenticatedSupplierPricingRoute
  '/supplier/profile': typeof AuthenticatedSupplierProfileRoute
  '/supplier/promotions': typeof AuthenticatedSupplierPromotionsRoute
  '/supplier/reports': typeof AuthenticatedSupplierReportsRoute
  '/supplier/reviews': typeof AuthenticatedSupplierReviewsRoute
  '/supplier/settings': typeof AuthenticatedSupplierSettingsRoute
  '/supplier/support': typeof AuthenticatedSupplierSupportRoute
  '/supplier/warehouse': typeof AuthenticatedSupplierWarehouseRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/supplier/customers/$id': typeof AuthenticatedSupplierCustomersIdRoute
  '/supplier/orders/$id': typeof AuthenticatedSupplierOrdersIdRoute
  '/supplier/products/$id': typeof AuthenticatedSupplierProductsIdRoute
  '/supplier/products/new': typeof AuthenticatedSupplierProductsNewRoute
  '/supplier/products': typeof AuthenticatedSupplierProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/marketplace': typeof MarketplaceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suppliers': typeof SuppliersRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/addresses': typeof AuthenticatedAddressesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/buyer': typeof AuthenticatedBuyerRouteWithChildren
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/seller': typeof AuthenticatedSellerRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/wishlist': typeof AuthenticatedWishlistRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/cms': typeof AuthenticatedAdminCmsRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/_authenticated/buyer/dashboard': typeof AuthenticatedBuyerDashboardRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/_authenticated/seller/dashboard': typeof AuthenticatedSellerDashboardRoute
  '/_authenticated/supplier/analytics': typeof AuthenticatedSupplierAnalyticsRoute
  '/_authenticated/supplier/customers': typeof AuthenticatedSupplierCustomersRouteWithChildren
  '/_authenticated/supplier/documents': typeof AuthenticatedSupplierDocumentsRoute
  '/_authenticated/supplier/inventory': typeof AuthenticatedSupplierInventoryRoute
  '/_authenticated/supplier/notifications': typeof AuthenticatedSupplierNotificationsRoute
  '/_authenticated/supplier/orders': typeof AuthenticatedSupplierOrdersRouteWithChildren
  '/_authenticated/supplier/payments': typeof AuthenticatedSupplierPaymentsRoute
  '/_authenticated/supplier/pricing': typeof AuthenticatedSupplierPricingRoute
  '/_authenticated/supplier/profile': typeof AuthenticatedSupplierProfileRoute
  '/_authenticated/supplier/promotions': typeof AuthenticatedSupplierPromotionsRoute
  '/_authenticated/supplier/reports': typeof AuthenticatedSupplierReportsRoute
  '/_authenticated/supplier/reviews': typeof AuthenticatedSupplierReviewsRoute
  '/_authenticated/supplier/settings': typeof AuthenticatedSupplierSettingsRoute
  '/_authenticated/supplier/support': typeof AuthenticatedSupplierSupportRoute
  '/_authenticated/supplier/warehouse': typeof AuthenticatedSupplierWarehouseRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/supplier/customers/$id': typeof AuthenticatedSupplierCustomersIdRoute
  '/_authenticated/supplier/orders/$id': typeof AuthenticatedSupplierOrdersIdRoute
  '/_authenticated/supplier/products/$id': typeof AuthenticatedSupplierProductsIdRoute
  '/_authenticated/supplier/products/new': typeof AuthenticatedSupplierProductsNewRoute
  '/_authenticated/supplier/products/': typeof AuthenticatedSupplierProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/contact'
    | '/forgot-password'
    | '/marketplace'
    | '/reset-password'
    | '/suppliers'
    | '/unauthorized'
    | '/addresses'
    | '/admin'
    | '/buyer'
    | '/checkout'
    | '/help'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/payments'
    | '/profile'
    | '/seller'
    | '/settings'
    | '/wishlist'
    | '/categories/$slug'
    | '/products/$slug'
    | '/suppliers/$id'
    | '/categories/'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/cms'
    | '/admin/coupons'
    | '/admin/finance'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/verifications'
    | '/buyer/dashboard'
    | '/orders/$id'
    | '/seller/dashboard'
    | '/supplier/analytics'
    | '/supplier/customers'
    | '/supplier/documents'
    | '/supplier/inventory'
    | '/supplier/notifications'
    | '/supplier/orders'
    | '/supplier/payments'
    | '/supplier/pricing'
    | '/supplier/profile'
    | '/supplier/promotions'
    | '/supplier/reports'
    | '/supplier/reviews'
    | '/supplier/settings'
    | '/supplier/support'
    | '/supplier/warehouse'
    | '/admin/'
    | '/supplier/customers/$id'
    | '/supplier/orders/$id'
    | '/supplier/products/$id'
    | '/supplier/products/new'
    | '/supplier/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/forgot-password'
    | '/marketplace'
    | '/reset-password'
    | '/suppliers'
    | '/unauthorized'
    | '/addresses'
    | '/buyer'
    | '/checkout'
    | '/help'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/payments'
    | '/profile'
    | '/seller'
    | '/settings'
    | '/wishlist'
    | '/categories/$slug'
    | '/products/$slug'
    | '/suppliers/$id'
    | '/categories'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/cms'
    | '/admin/coupons'
    | '/admin/finance'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/verifications'
    | '/buyer/dashboard'
    | '/orders/$id'
    | '/seller/dashboard'
    | '/supplier/analytics'
    | '/supplier/customers'
    | '/supplier/documents'
    | '/supplier/inventory'
    | '/supplier/notifications'
    | '/supplier/orders'
    | '/supplier/payments'
    | '/supplier/pricing'
    | '/supplier/profile'
    | '/supplier/promotions'
    | '/supplier/reports'
    | '/supplier/reviews'
    | '/supplier/settings'
    | '/supplier/support'
    | '/supplier/warehouse'
    | '/admin'
    | '/supplier/customers/$id'
    | '/supplier/orders/$id'
    | '/supplier/products/$id'
    | '/supplier/products/new'
    | '/supplier/products'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/contact'
    | '/forgot-password'
    | '/marketplace'
    | '/reset-password'
    | '/suppliers'
    | '/unauthorized'
    | '/_authenticated/addresses'
    | '/_authenticated/admin'
    | '/_authenticated/buyer'
    | '/_authenticated/checkout'
    | '/_authenticated/help'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/orders'
    | '/_authenticated/payments'
    | '/_authenticated/profile'
    | '/_authenticated/seller'
    | '/_authenticated/settings'
    | '/_authenticated/wishlist'
    | '/categories/$slug'
    | '/products/$slug'
    | '/suppliers/$id'
    | '/categories/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/cms'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/finance'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/security'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/verifications'
    | '/_authenticated/buyer/dashboard'
    | '/_authenticated/orders/$id'
    | '/_authenticated/seller/dashboard'
    | '/_authenticated/supplier/analytics'
    | '/_authenticated/supplier/customers'
    | '/_authenticated/supplier/documents'
    | '/_authenticated/supplier/inventory'
    | '/_authenticated/supplier/notifications'
    | '/_authenticated/supplier/orders'
    | '/_authenticated/supplier/payments'
    | '/_authenticated/supplier/pricing'
    | '/_authenticated/supplier/profile'
    | '/_authenticated/supplier/promotions'
    | '/_authenticated/supplier/reports'
    | '/_authenticated/supplier/reviews'
    | '/_authenticated/supplier/settings'
    | '/_authenticated/supplier/support'
    | '/_authenticated/supplier/warehouse'
    | '/_authenticated/admin/'
    | '/_authenticated/supplier/customers/$id'
    | '/_authenticated/supplier/orders/$id'
    | '/_authenticated/supplier/products/$id'
    | '/_authenticated/supplier/products/new'
    | '/_authenticated/supplier/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRouteWithChildren
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  MarketplaceRoute: typeof MarketplaceRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuppliersRoute: typeof SuppliersRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/suppliers/$id': {
      id: '/suppliers/$id'
      path: '/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof SuppliersIdRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/_authenticated/wishlist': {
      id: '/_authenticated/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AuthenticatedWishlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seller': {
      id: '/_authenticated/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof AuthenticatedSellerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buyer': {
      id: '/_authenticated/buyer'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof AuthenticatedBuyerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/addresses': {
      id: '/_authenticated/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AuthenticatedAddressesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/supplier/warehouse': {
      id: '/_authenticated/supplier/warehouse'
      path: '/supplier/warehouse'
      fullPath: '/supplier/warehouse'
      preLoaderRoute: typeof AuthenticatedSupplierWarehouseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/support': {
      id: '/_authenticated/supplier/support'
      path: '/supplier/support'
      fullPath: '/supplier/support'
      preLoaderRoute: typeof AuthenticatedSupplierSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/settings': {
      id: '/_authenticated/supplier/settings'
      path: '/supplier/settings'
      fullPath: '/supplier/settings'
      preLoaderRoute: typeof AuthenticatedSupplierSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/reviews': {
      id: '/_authenticated/supplier/reviews'
      path: '/supplier/reviews'
      fullPath: '/supplier/reviews'
      preLoaderRoute: typeof AuthenticatedSupplierReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/reports': {
      id: '/_authenticated/supplier/reports'
      path: '/supplier/reports'
      fullPath: '/supplier/reports'
      preLoaderRoute: typeof AuthenticatedSupplierReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/promotions': {
      id: '/_authenticated/supplier/promotions'
      path: '/supplier/promotions'
      fullPath: '/supplier/promotions'
      preLoaderRoute: typeof AuthenticatedSupplierPromotionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/profile': {
      id: '/_authenticated/supplier/profile'
      path: '/supplier/profile'
      fullPath: '/supplier/profile'
      preLoaderRoute: typeof AuthenticatedSupplierProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/pricing': {
      id: '/_authenticated/supplier/pricing'
      path: '/supplier/pricing'
      fullPath: '/supplier/pricing'
      preLoaderRoute: typeof AuthenticatedSupplierPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/payments': {
      id: '/_authenticated/supplier/payments'
      path: '/supplier/payments'
      fullPath: '/supplier/payments'
      preLoaderRoute: typeof AuthenticatedSupplierPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/orders': {
      id: '/_authenticated/supplier/orders'
      path: '/supplier/orders'
      fullPath: '/supplier/orders'
      preLoaderRoute: typeof AuthenticatedSupplierOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/notifications': {
      id: '/_authenticated/supplier/notifications'
      path: '/supplier/notifications'
      fullPath: '/supplier/notifications'
      preLoaderRoute: typeof AuthenticatedSupplierNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/inventory': {
      id: '/_authenticated/supplier/inventory'
      path: '/supplier/inventory'
      fullPath: '/supplier/inventory'
      preLoaderRoute: typeof AuthenticatedSupplierInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/documents': {
      id: '/_authenticated/supplier/documents'
      path: '/supplier/documents'
      fullPath: '/supplier/documents'
      preLoaderRoute: typeof AuthenticatedSupplierDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/customers': {
      id: '/_authenticated/supplier/customers'
      path: '/supplier/customers'
      fullPath: '/supplier/customers'
      preLoaderRoute: typeof AuthenticatedSupplierCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/analytics': {
      id: '/_authenticated/supplier/analytics'
      path: '/supplier/analytics'
      fullPath: '/supplier/analytics'
      preLoaderRoute: typeof AuthenticatedSupplierAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seller/dashboard': {
      id: '/_authenticated/seller/dashboard'
      path: '/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof AuthenticatedSellerDashboardRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
    '/_authenticated/buyer/dashboard': {
      id: '/_authenticated/buyer/dashboard'
      path: '/dashboard'
      fullPath: '/buyer/dashboard'
      preLoaderRoute: typeof AuthenticatedBuyerDashboardRouteImport
      parentRoute: typeof AuthenticatedBuyerRoute
    }
    '/_authenticated/admin/verifications': {
      id: '/_authenticated/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AuthenticatedAdminVerificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/security': {
      id: '/_authenticated/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AuthenticatedAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/finance': {
      id: '/_authenticated/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cms': {
      id: '/_authenticated/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AuthenticatedAdminCmsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/supplier/products/': {
      id: '/_authenticated/supplier/products/'
      path: '/supplier/products'
      fullPath: '/supplier/products/'
      preLoaderRoute: typeof AuthenticatedSupplierProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/products/new': {
      id: '/_authenticated/supplier/products/new'
      path: '/supplier/products/new'
      fullPath: '/supplier/products/new'
      preLoaderRoute: typeof AuthenticatedSupplierProductsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/products/$id': {
      id: '/_authenticated/supplier/products/$id'
      path: '/supplier/products/$id'
      fullPath: '/supplier/products/$id'
      preLoaderRoute: typeof AuthenticatedSupplierProductsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier/orders/$id': {
      id: '/_authenticated/supplier/orders/$id'
      path: '/$id'
      fullPath: '/supplier/orders/$id'
      preLoaderRoute: typeof AuthenticatedSupplierOrdersIdRouteImport
      parentRoute: typeof AuthenticatedSupplierOrdersRoute
    }
    '/_authenticated/supplier/customers/$id': {
      id: '/_authenticated/supplier/customers/$id'
      path: '/$id'
      fullPath: '/supplier/customers/$id'
      preLoaderRoute: typeof AuthenticatedSupplierCustomersIdRouteImport
      parentRoute: typeof AuthenticatedSupplierCustomersRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminCmsRoute: typeof AuthenticatedAdminCmsRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminSecurityRoute: typeof AuthenticatedAdminSecurityRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVerificationsRoute: typeof AuthenticatedAdminVerificationsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminCmsRoute: AuthenticatedAdminCmsRoute,
  AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
  AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminSecurityRoute: AuthenticatedAdminSecurityRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVerificationsRoute: AuthenticatedAdminVerificationsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedBuyerRouteChildren {
  AuthenticatedBuyerDashboardRoute: typeof AuthenticatedBuyerDashboardRoute
}

const AuthenticatedBuyerRouteChildren: AuthenticatedBuyerRouteChildren = {
  AuthenticatedBuyerDashboardRoute: AuthenticatedBuyerDashboardRoute,
}

const AuthenticatedBuyerRouteWithChildren =
  AuthenticatedBuyerRoute._addFileChildren(AuthenticatedBuyerRouteChildren)

interface AuthenticatedOrdersRouteChildren {
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRoute
}

const AuthenticatedOrdersRouteChildren: AuthenticatedOrdersRouteChildren = {
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRoute,
}

const AuthenticatedOrdersRouteWithChildren =
  AuthenticatedOrdersRoute._addFileChildren(AuthenticatedOrdersRouteChildren)

interface AuthenticatedSellerRouteChildren {
  AuthenticatedSellerDashboardRoute: typeof AuthenticatedSellerDashboardRoute
}

const AuthenticatedSellerRouteChildren: AuthenticatedSellerRouteChildren = {
  AuthenticatedSellerDashboardRoute: AuthenticatedSellerDashboardRoute,
}

const AuthenticatedSellerRouteWithChildren =
  AuthenticatedSellerRoute._addFileChildren(AuthenticatedSellerRouteChildren)

interface AuthenticatedSupplierCustomersRouteChildren {
  AuthenticatedSupplierCustomersIdRoute: typeof AuthenticatedSupplierCustomersIdRoute
}

const AuthenticatedSupplierCustomersRouteChildren: AuthenticatedSupplierCustomersRouteChildren =
  {
    AuthenticatedSupplierCustomersIdRoute:
      AuthenticatedSupplierCustomersIdRoute,
  }

const AuthenticatedSupplierCustomersRouteWithChildren =
  AuthenticatedSupplierCustomersRoute._addFileChildren(
    AuthenticatedSupplierCustomersRouteChildren,
  )

interface AuthenticatedSupplierOrdersRouteChildren {
  AuthenticatedSupplierOrdersIdRoute: typeof AuthenticatedSupplierOrdersIdRoute
}

const AuthenticatedSupplierOrdersRouteChildren: AuthenticatedSupplierOrdersRouteChildren =
  {
    AuthenticatedSupplierOrdersIdRoute: AuthenticatedSupplierOrdersIdRoute,
  }

const AuthenticatedSupplierOrdersRouteWithChildren =
  AuthenticatedSupplierOrdersRoute._addFileChildren(
    AuthenticatedSupplierOrdersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAddressesRoute: typeof AuthenticatedAddressesRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBuyerRoute: typeof AuthenticatedBuyerRouteWithChildren
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRouteWithChildren
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSellerRoute: typeof AuthenticatedSellerRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWishlistRoute: typeof AuthenticatedWishlistRoute
  AuthenticatedSupplierAnalyticsRoute: typeof AuthenticatedSupplierAnalyticsRoute
  AuthenticatedSupplierCustomersRoute: typeof AuthenticatedSupplierCustomersRouteWithChildren
  AuthenticatedSupplierDocumentsRoute: typeof AuthenticatedSupplierDocumentsRoute
  AuthenticatedSupplierInventoryRoute: typeof AuthenticatedSupplierInventoryRoute
  AuthenticatedSupplierNotificationsRoute: typeof AuthenticatedSupplierNotificationsRoute
  AuthenticatedSupplierOrdersRoute: typeof AuthenticatedSupplierOrdersRouteWithChildren
  AuthenticatedSupplierPaymentsRoute: typeof AuthenticatedSupplierPaymentsRoute
  AuthenticatedSupplierPricingRoute: typeof AuthenticatedSupplierPricingRoute
  AuthenticatedSupplierProfileRoute: typeof AuthenticatedSupplierProfileRoute
  AuthenticatedSupplierPromotionsRoute: typeof AuthenticatedSupplierPromotionsRoute
  AuthenticatedSupplierReportsRoute: typeof AuthenticatedSupplierReportsRoute
  AuthenticatedSupplierReviewsRoute: typeof AuthenticatedSupplierReviewsRoute
  AuthenticatedSupplierSettingsRoute: typeof AuthenticatedSupplierSettingsRoute
  AuthenticatedSupplierSupportRoute: typeof AuthenticatedSupplierSupportRoute
  AuthenticatedSupplierWarehouseRoute: typeof AuthenticatedSupplierWarehouseRoute
  AuthenticatedSupplierProductsIdRoute: typeof AuthenticatedSupplierProductsIdRoute
  AuthenticatedSupplierProductsNewRoute: typeof AuthenticatedSupplierProductsNewRoute
  AuthenticatedSupplierProductsIndexRoute: typeof AuthenticatedSupplierProductsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAddressesRoute: AuthenticatedAddressesRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBuyerRoute: AuthenticatedBuyerRouteWithChildren,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRouteWithChildren,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSellerRoute: AuthenticatedSellerRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWishlistRoute: AuthenticatedWishlistRoute,
  AuthenticatedSupplierAnalyticsRoute: AuthenticatedSupplierAnalyticsRoute,
  AuthenticatedSupplierCustomersRoute:
    AuthenticatedSupplierCustomersRouteWithChildren,
  AuthenticatedSupplierDocumentsRoute: AuthenticatedSupplierDocumentsRoute,
  AuthenticatedSupplierInventoryRoute: AuthenticatedSupplierInventoryRoute,
  AuthenticatedSupplierNotificationsRoute:
    AuthenticatedSupplierNotificationsRoute,
  AuthenticatedSupplierOrdersRoute:
    AuthenticatedSupplierOrdersRouteWithChildren,
  AuthenticatedSupplierPaymentsRoute: AuthenticatedSupplierPaymentsRoute,
  AuthenticatedSupplierPricingRoute: AuthenticatedSupplierPricingRoute,
  AuthenticatedSupplierProfileRoute: AuthenticatedSupplierProfileRoute,
  AuthenticatedSupplierPromotionsRoute: AuthenticatedSupplierPromotionsRoute,
  AuthenticatedSupplierReportsRoute: AuthenticatedSupplierReportsRoute,
  AuthenticatedSupplierReviewsRoute: AuthenticatedSupplierReviewsRoute,
  AuthenticatedSupplierSettingsRoute: AuthenticatedSupplierSettingsRoute,
  AuthenticatedSupplierSupportRoute: AuthenticatedSupplierSupportRoute,
  AuthenticatedSupplierWarehouseRoute: AuthenticatedSupplierWarehouseRoute,
  AuthenticatedSupplierProductsIdRoute: AuthenticatedSupplierProductsIdRoute,
  AuthenticatedSupplierProductsNewRoute: AuthenticatedSupplierProductsNewRoute,
  AuthenticatedSupplierProductsIndexRoute:
    AuthenticatedSupplierProductsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CategoriesRouteChildren {
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesSlugRoute: CategoriesSlugRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

interface SuppliersRouteChildren {
  SuppliersIdRoute: typeof SuppliersIdRoute
}

const SuppliersRouteChildren: SuppliersRouteChildren = {
  SuppliersIdRoute: SuppliersIdRoute,
}

const SuppliersRouteWithChildren = SuppliersRoute._addFileChildren(
  SuppliersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRouteWithChildren,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  MarketplaceRoute: MarketplaceRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuppliersRoute: SuppliersRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
  ProductsSlugRoute: ProductsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
